### PR TITLE
Add linux to MINLPTests CI job

### PR DESCRIPTION
**Pull request by odow**
Bonmin fails on Linux:

```Julia
julia> using JuMP, AmplNLWriter, Bonmin_jll

julia> model = Model(() -> AmplNLWriter.Optimizer(Bonmin_jll.amplexe))
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: EMPTY_OPTIMIZER
Solver name: AmplNLWriter

julia> @variable(model, x >= 0)
x

julia> @objective(model, Min, x)
x

julia> optimize!(model)
Bonmin 1.8.8 using Cbc 2.10.5 and Ipopt 3.13.4
bonmin: 
Cbc3007W No integer variables - nothing to do

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit https://github.com/coin-or/Ipopt
******************************************************************************

NLP0012I 
              Num      Status      Obj             It       time                 Location
NLP0014I             1   UNBOUNDED 4.6010295e+22       34 0.053675
NLP0014I             2   UNBOUNDED 4.6010295e+22       34 0.031139
Cbc3007W No integer variables - nothing to do
Cbc0034I The LP relaxation is unbounded!

 	"Finished"

julia> versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```

### CODE REVIEW

**Comment by odow** [comment]
@tkralphs I've been working on packaging Bonmin and Couenne for JuMP. 

AmplNLWriter.jl needs a new release, but then you will be able to go:
```Julia
import Pkg
Pkg.add("Bonmin_jll")   # Automatically installs Bonmin binaries  
Pkg.add("Couenne_jll")  # Automatically installs Couenne binaries
using JuMP, AmplNLWriter, Bonmin_jll, Couenne_jll

# Create a model with Bonmin
model = Model() do
    AmplNLWriter.Optimizer(Bonmin_jll.amplexe)
end

# Create a model with Couenne
model = Model() do
    AmplNLWriter.Optimizer(Couenne_jll.amplexe)
end
```

This currently works on Windows (!!! [ci job](https://github.com/jump-dev/AmplNLWriter.jl/pull/132/checks?check_run_id=2327424824)) and Mac, but I'm getting incorrect solutions on Linux (e.g., the post above, or [this ci job](https://github.com/jump-dev/AmplNLWriter.jl/pull/132/checks?check_run_id=2327424728)). 

Have you seen these before? Any pointers on where to start looking?

Here's our build script:
https://github.com/JuliaPackaging/Yggdrasil/blob/master/C/Coin-OR/Bonmin/build_tarballs.jl
Where using Cbc 2.10.5 and Ipopt 3.13.4.

**Comment by tkralphs** [comment]
Hmm, I don't have a very good idea about what's happening, but I got a couple of clues just playing around. If I pass a Bonmin executable I built myself to AmplNLWriter with the simple model you built above, it works fine. The version I'm using is a weird combination of stable/1.8 of Bonmin, stable/2.10 of Cbc, and master of Ipopt. I'm not entirely sure why I built that one, I just grabbed the one I could find most easily and it worked. Another clue is that if I solve the problem with Couenne_jll or Ipopt_jll, it also works. So there is something particular about Bonmin, at least in this one example. 

With that said, however, the whole thing seems to pivot on how Ipopt behaves. In the case where Bonmin fails, Ipopt reports the relaxation is unbounded. In the other cases, it doesn't. So there is something different about the way Ipopt is behaving in each case. I guess some parameters may be set differently, but I'm not enough of an expert to know exactly what to try to figure out what's going on. If you can isolate the Ipopt setup, maybe you can replicate the bug just within Ipopt and @svigerske can maybe give some advice.

**Comment by odow** [comment]
Ah. We had a problem with Ipopt and the version of MUMPS: https://github.com/jump-dev/Ipopt.jl/issues/246. I guess it's related.

> If you can isolate the Ipopt setup

The weird thing is that you can replicate the exact version of Ipopt, and it works fine:
```Julia
using JuMP, AmplNLWriter, Ipopt_jll
model = Model(() -> AmplNLWriter.Optimizer(Ipopt_jll.amplexe))
@variable(model, x >= 0)
@objective(model, Min, x)
optimize!(model)
```

Here's the build script:
https://github.com/JuliaPackaging/Yggdrasil/blob/master/I/Ipopt/build_tarballs.jl

I did just spot one difference. Ipopt_jll was built with `OpenBLAS32_jll@0.3.9`, but here we're using `OpenBLAS32_jll@0.3.12`. I guess that's fine for Ipopt, but there may be some compatibility issue when we built Bonmin. I just pushed a commit which should force `OpenBLAS32_jll@0.3.9` to see if that makes a difference.

**Comment by tkralphs** [comment]
I poked around in the build files and there seems to be some inconsistency, which may or may not be the source of problems. I can't really tell exactly what's going on without understanding better the way in which Julia sets up paths and things internally. But there definitely are some improvements to be made in the build setup. I'd be happy to have a face-to-face if you want to walk me through some things so I can advise you a bit on how to tighten up.

One thing I noticed is the library dependencies are inconsistent between `couenne`, `bonmin`, and `ipopt`. Just running `ldd` on the binaries, `couenne` doesn't seem to depend on MUMPS at all, `ipopt` only depends on `libdmumps` (which matches the build recipe), while `bonmin` depends on what looks like all `lib*mumps`. I don't know much about MUMPS or why there is `libcmumps`, `libdmumps`, etc. 

The configure flags are also very different. For building `bonmin`, there is a flag
```
--with-bonmin-lib="-lbonminampl -lbonmin -lipoptamplinterface -lipopt -lCbc -lCgl -lOsiClp -lClp -lOsi -lCoinUtils -lasl -lopenblas"
```
whereas for building `couenne`, there is nothing. For `cbc`, you have the full complement
```
--with-coinutils-lib="-lCoinUtils" \
--with-osi-lib="-lOsi -lCoinUtils" \
--with-clp-lib="-lClp -lOsiClp -lCoinUtils" \
--with-cgl-lib="-lCgl -lClp -lOsiClp -lOsi -lCoinUtils" \
--with-coindepend-lib="-lCgl -lClp -lOsiClp -lOsi -lCoinUtils" \
```
The `.pc` files are also very different. The ones for Ipopt and Couenne seem to have been hacked so that they have no explicit dependencies. Ipopt looks like this:
```
prefix=/workspace/destdir
#prefix=${pcfiledir}/../..
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include/coin-or

Name: Ipopt
Description: Interior Point Optimizer
URL: https://github.com/coin-or/Ipopt
Version: 3.13.4
Cflags: -I${includedir}
Libs: -L${libdir} -lipopt
Requires.private:
#Libs: -L${libdir} -lipopt -L/workspace/destdir/lib -ldmumps -lmpiseq -lmumps_common -lopenblas -lpord -lopenblas -lm  -ldl
#Requires:
```
while Couenne looks like this
```
prefix=/workspace/destdir
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include/coin

Name: Couenne
Description: Convex Over and Under Envelopes for Nonlinear Estimation
URL: https://projects.coin-or.org/Couenne
Version: 0.5.8
Libs: -L${libdir} -lCouenne -lasl -lipoptamplinterface -lbonminampl -lbonmin -lipoptamplinterface -lipopt -lCbc -lCgl -lOsiClp -lClp -lOsi -lCoinUtils -lasl -lopenblas
Cflags: -I${includedir}
Requires:
```
But what is strange is that Bonmin has explicit dependencies.
```
prefix=/workspace/destdir
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include/coin

Name: Bonmin
Description: Basic Open-source Nonlinear Mixed Integer programming
URL: https://projects.coin-or.org/Bonmin
Version: 1.8.8
Libs: -L${libdir} -lbonmin
Cflags: -I${includedir}
Requires: cbc osi-clp ipopt
```
pkg-config is how our configure scripts are set up to find dependent projects if they're not explicitly specified on the command line. I don't know exactly how Couenne is finding its dependencies, but it must be through pkg-config, since they aren't specified any other way I can. But then it could be picking up pkg-config files from the system if Julia doesn't take care of `PKG_CONFIG_PATH`. There look to be a lot of ways to get weird mixes of libraries. 

Another thing to note is that when I do `ldd` on the binaries, a lot of dependencies can't be found, which I guess means that they are only picked up somehow through the setting of the library search path internal to Julia. But some of the COIN-OR libraries installed in system locations on my computer outside of Julia _do_ get picked up instead of the ones installed by Julia. I'm not sure how Julia ensures that it's the libraries installed by Julia that get picked up and not system libraries with the same name.

Anyway, I'm sure I have a very little understanding of how all this hangs together, but it really looks like it could use some cleanup. Happy to help if needed.

And by the way, this is all going to change with the new versions coming out that use the revamped build system.

**Comment by odow** [comment]
> I'm sure I have a very little understanding of how all this hangs together

Me too...

> a lot of dependencies can't be found, which I guess means that they are only picked up somehow through the setting of the library search path internal to Julia.

Yes. There is an `__init__` function in the JLLs which load the dependent JLLs. Each JLL declares the list of libraries it exports, and these are the ones that are loaded. You would probably run into trouble if you went `import Libdl; dlopen("libcbc")  # <- the system cbc in your path` and then ran `using Cbc_jll`. 

> There look to be a lot of ways to get weird mixes of libraries.

A lot of this has just been trial-and-error to get things working. The scripts are a mix of different people at different times, so there isn't one unified COIN-OR script.

> I'd be happy to have a face-to-face if you want to walk me through some things so I can advise you a bit on how to tighten up.

I'm all ears. When suits?

**Comment by odow** [comment]
We're playing whack-a-mole. Linux now runs, but everything is hitting some assertion
```
Bonmin 1.8.8 using Cbc 2.10.5 and Ipopt 3.13.4
3474
bonmin: bonmin.nlp_log_level=0
3475

3476

3477
******************************************************************************
3478
This program contains Ipopt, a library for large-scale nonlinear optimization.
3479
 Ipopt is released as open source code under the Eclipse Public License (EPL).
3480
         For more information visit https://github.com/coin-or/Ipopt
3481
******************************************************************************
3482

3483
Cbc0012I Integer solution of -6.1415927 found by DiveMIPFractional after 0 iterations and 0 nodes (0.02 seconds)
3484
bonmin: ../../../../Osi/src/Osi/OsiBranchingObject.cpp:621: virtual OsiBranchingObject* OsiSimpleInteger::createBranch(OsiSolverInterface*, const OsiBranchingInformation*, int) const: Assertion `fabs(value - nearest) > info->integerTolerance_' failed.
3485
nlp_mi_003_016: Test Failed at /home/runner/.julia/packages/MINLPTests/oQKO1/src/MINLPTests.jl:56
3486
  Expression: JuMP.termination_status(model) == termination_target[problem_type]
3487
   Evaluated: MathOptInterface.OTHER_ERROR == MathOptInterface.LOCALLY_SOLVED
```

**Comment by tkralphs** [comment]
Hmm, it's difficult to guess what's going on with this. I'm not surprised to see some issues arising now, since Bonmin and Couenne don't have very rigorous test harnesses and are certainly not as robust as Cbc. Do tests pass with NDEBUG undefined? This looks like it's probably a mismatch of tolerances somewhere. If the tolerance applied here is not the same as the one Bonmin itself is using, this could trigger this kind of assert. Debugging it might be a bit of work. If you dump to nl file and replicate in stand-alone Bonmin, maybe the best is to open an issue.

**Comment by odow** [comment]
I was beginning to think I would never see the day! Bonmin and Couenne passing all tests. I have @giordano to thank for the incredible amount of help along the way.

**Comment by tkralphs** [comment]
Nice work! So what was the issue finally?

**Comment by odow** [comment]
I needed to recompile Osi.

It was a bit of work, but I think we're now in a good place, where everything had been built with the same underlying version, and we're up-to-date on the latest release version of all COIN packages.

**Comment by tkralphs** [comment]
Great!

**Pull request merged**
