### PR TITLE
Debug ipopt.exe on Windows

### PR DESCRIPTION
**Pull request by amontoison**
@odow

### CODE REVIEW

**Comment by odow** [comment]
I ran your job in the other PR: https://github.com/jump-dev/AmplNLWriter.jl/actions/runs/4932867963/jobs/8816294372?pr=163

**Comment by odow** [comment]
I've added you as a maintainer, so you should be able to push a branch to the `jump-dev` remote without me having to approve PRs.

**Comment by amontoison** [comment]
Thanks @odow!

**Comment by amontoison** [comment]
@odow I have different errors here. :thinking:

**Comment by odow** [comment]
> I have different errors here

See https://github.com/jump-dev/AmplNLWriter.jl/pull/163/files#r1189342334

**Comment by odow** [comment]
Okay. Now we have the same issue. So you should be able to muck with the JLL on your branch to see what happens.

**Comment by amontoison** [comment]
Ok, now let's find the culprit.

- Test 1 :x:
  - Ipopt 3.14.4
  - OpenBLAS 3.0.23 (no compat entry)
  - MUMPS_seq 500.500.101
  - METIS 5.1.2 (no compat entry)
  
- Test 2 :x:
  - Ipopt 3.14.4
  - OpenBLAS 3.0.10
  - MUMPS_seq 500.500.101
  - METIS 5.1.2 (no compat entry)

**Comment by odow** [comment]
Can we reproduce the existing 3.14.4 binary and then work forwards?

**Comment by amontoison** [comment]
I tried and I can't pass the tests :(

**Comment by amontoison** [comment]
Oscar, I just remarked this option: https://github.com/JuliaPackaging/Yggdrasil/blob/master/C/Coin-OR/Ipopt/build_tarballs.jl#L42
Did we forget `--`?

**Comment by odow** [comment]
This must be a issue with BinaryBuilder.jl then. What if you try compiling with an older version?

**Comment by odow** [comment]
> Did we forget --?

I don't think so. All the COIN-OR stuff has it

**Comment by odow** [comment]
Closing in favor of #163

**Pull request closed without merging**
